// angular/src/app/pages/home/home.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Coffee, Roast } from '../../models/coffee';
import { CoffeeService } from '../../services/coffee.service';

type SortableKey = 'name' | 'origin' | 'body' | 'bitterness' | 'price';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  private svc = inject(CoffeeService);
  coffees = signal<Coffee[] | null>(null);
  error = signal<string | null>(null);
  sortKey = signal<SortableKey | null>(null);
  roastFilter = signal<Roast | null>(null);

  constructor() {
    this.svc.list().subscribe({
      next: (data) => this.coffees.set(data),
      error: () => this.error.set('Failed to load coffees')
    });
  }

  sortedCoffees = computed(() => {
    const key = this.sortKey();
    const roast = this.roastFilter();
    const coffees = this.coffees();
    if (!coffees) return coffees;
    const filtered = roast ? coffees.filter(c => c.roast === roast) : coffees;
    if (!key) return filtered;
    return [...filtered].sort((a, b) => {
      const av = a[key], bv = b[key];
      if (typeof av === 'number' && typeof bv === 'number') return av - bv;
      return String(av).localeCompare(String(bv));
    });
  });
}

<div class="container py-4">
  <h1 class="display-5 fw-semibold mb-3">Coffee2Live</h1>
  <p class="text-secondary mb-4">Curated coffees you will love.</p>

  <div *ngIf="error()" class="alert alert-danger">{{ error() }}</div>
  <div *ngIf="!coffees() && !error()" class="text-secondary">Loading…</div>

  <div class="d-flex flex-wrap gap-3 mb-3" *ngIf="coffees()">
    <div>
      <label for="roastFilter" class="form-label me-2">Roast</label>
      <select id="roastFilter" class="form-select w-auto d-inline-block"
        (change)="roastFilter.set($any($event.target).value || null)">
        <option value="">— All —</option>
        <option value="light">Light</option>
        <option value="medium">Medium</option>
        <option value="dark">Dark</option>
      </select>
    </div>
    <div>
      <label for="sortSelect" class="form-label me-2">Sort by</label>
      <select id="sortSelect" class="form-select w-auto d-inline-block"
        (change)="sortKey.set($any($event.target).value || null)">
        <option value="">— None —</option>
        <option value="name">Name</option>
        <option value="origin">Origin</option>
        <option value="body">Body</option>
        <option value="bitterness">Bitterness</option>
        <option value="price">Price</option>
      </select>
    </div>
  </div>

  <div class="row g-3" *ngIf="sortedCoffees() as list">
    <div class="col-12 col-md-6 col-lg-4" *ngFor="let c of list">
      <div class="card coffee-card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ c.name }} ({{ c.price | currency }})</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ c.origin }}</h6>
          <p class="card-text small mb-2">{{ c.tastingNotes }}</p>
          <div class="small">
            <span class="badge text-bg-light me-1">Roast: {{ c.roast }}</span>
            <span class="badge text-bg-light me-1">Acidity: {{ c.acidity }}</span>
            <span class="badge text-bg-light me-1">Body: {{ c.body }}/5</span>
            <span class="badge text-bg-light me-1">Bitterness: {{ c.bitterness }}/10</span>
          </div>
        </div>
        <div class="card-footer text-muted small">Best for: {{ c.bestFor }}</div>
      </div>
    </div>
  </div>
</div>

// react/src/pages/Home/Home.tsx
import { useState, useEffect } from 'react'
import { Coffee } from '../../models/coffee'
import './Home.css'

const API_BASE = 'http://localhost:5000'

function Home() {
  const [coffees, setCoffees] = useState<Coffee[] | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch(`${API_BASE}/api/coffees`)
      .then(res => {
        if (!res.ok) throw new Error('Network response was not ok')
        return res.json()
      })
      .then((data: Coffee[]) => setCoffees(data))
      .catch(() => setError('Failed to load coffees'))
  }, [])

  return (
    <div className="container py-4">
      <h1 className="display-5 fw-semibold mb-3">Coffee2Live</h1>
      <p className="text-secondary mb-4">Curated coffees you will love.</p>

      {error && <div className="alert alert-danger">{error}</div>}
      {!coffees && !error && <div className="text-secondary">Loading…</div>}

      {coffees && (
        <div className="row g-3">
          {coffees.map(c => (
            <div key={c.id} className="col-12 col-md-6 col-lg-4">
              <div className="card coffee-card h-100">
                <div className="card-body">
                  <h5 className="card-title">{c.name}</h5>
                  <h6 className="card-subtitle mb-2 text-muted">{c.origin}</h6>
                  <p className="card-text small mb-2">{c.tastingNotes}</p>
                  <div className="small">
                    <span className="badge text-bg-light me-1">Roast: {c.roast}</span>
                    <span className="badge text-bg-light me-1">Acidity: {c.acidity}</span>
                    <span className="badge text-bg-light me-1">Body: {c.body}/5</span>
                    <span className="badge text-bg-light me-1">Bitterness: {c.bitterness}/10</span>
                  </div>
                </div>
                <div className="card-footer text-muted small">Best for: {c.bestFor}</div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default Home
